version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sghlds0804Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: EmployeePayroll
  gitServerName: bearerTokenArti_githubEnt_shared
  gitUrl: https://github.ibm.com/Arti-Khare
  gitUsername: Arti-Khare
  gitBranch: main
